import ConsultasSql
import mail
#import ManipuladorArchivos
import replace_files
#import ManipuladorArchivos
import res_partner
import res_currency_rate
import res_company
import account_invoice
#import res_currency
